manifest:
   remotes:
     - name: zmkfirmware
       url-base: https://github.com/petejohanson
     - name: pmw3360-driver
       url-base: https://github.com/trentrand
   projects:
     - name: zmk
       remote: zmkfirmware
       revision: feat/pointers-move-scroll
       import: app/west.yml
     - name: zmk-pmw3360-driver
       remote: pmw3360-driver
       revision: main
   self:
     path: config